os:
  - osx
  - linux
env:
  - TEST_SUITE=ios
  - TEST_SUITE=android
matrix:
    fast_finish: true
    exclude:
      - os: osx
        env: TEST_SUITE=ios
      - os: osx
        env: TEST_SUITE=android
      - os: linux
        env: TEST_SUITE=ios
      - os: linux
        env: TEST_SUITE=android
    include:
      - os: osx
        env: TEST_SUITE=ios
        osx_image: xcode8.3
        language: swift
        before_install:
          - brew update
          - brew install nvm
          - source $(brew --prefix nvm)/nvm.sh
          - nvm install 7
          - brew install ios-webkit-debug-proxy
        script:
          - PLATFORM=ios make travis
      - os: linux
        env: TEST_SUITE=android
        jdk: oraclejdk8
        language: android
        android:
          components:
            - tools
            - build-tools-25.0.2
            - platform-tools
            - extra-android-m2repository
            - extra-google-android-support
            - android-25
        sudo: required
        before_install:
          - export CHROME_BIN=chromium-browser
          - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
          - export ANDROID_HOME=/usr/local/android-sdk
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
        before_script:
          - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
          - unzip gradle-3.3-all.zip > /dev/null
          - export GRADLE_HOME=$PWD/gradle-3.3
          - export PATH=$GRADLE_HOME/bin:$PATH
          - . $HOME/.nvm/nvm.sh
          - nvm install 7
          - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
          - emulator -avd test -no-audio -no-window &
          - android-wait-for-emulator
          - adb shell input keyevent 82 &
        script:
          - PLATFORM=android make travis
